name: Dependabot auto-approve
on:
  push:
    branches:
      - master
    paths-ignore:
      - '**/*README*'
  # merge_group:
    # types: [checks_requested]
  # check_suite:
jobs:
  dependabot:
    runs-on: ubuntu-latest
    if: github.actor == 'nileshgadgi'
    steps:
      # - name: Dependabot metadata
      #   id: metadata
      #   uses: dependabot/fetch-metadata@v1
      #   with:
      #     github-token: "${{ secrets.GITHUB_TOKEN }}"
      - name: testing
        run: echo "triggered";