name: Auto approve and merge PRs by dependabot
on:
  pull_request:
    types:
      - labeled
      - synchronize
      - opened
      - ready_for_review
      - reopened
  check_run:
      types: 
      - completed
permissions:
  pull-requests: write
jobs:
  autoapprove:
    name: Auto Approve a PR by dependabot
    runs-on: ubuntu-latest
    steps:
      - name: Auto Approve
        run: |
          gh pr review -R ${{ github.repository }} -B ${{ github.event.pull_request.head.ref }} --approve
    #   - name: Auto approve
    #     uses: hmarr/auto-approve-action@v3.2.1
    #     # Perform the auto approve action only when the PR is raised by dependabot
    #     if: github.actor == 'dependabot[bot]'
    #     with:
    #       github-token: '${{ secrets.GITHUB }}'
  automerge:
    runs-on: ubuntu-latest
    steps:
      - id: automerge
        name: automerge
        uses: pascalgn/automerge-action@v0.15.6
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          MERGE_FILTER_AUTHOR: 'dependabot[bot]'
          MERGE_METHOD: "merge"
          MERGE_DELETE_BRANCH: "true"
          MERGE_LABELS: "dependencies,automerge"
          MERGE_REQUIRED_APPROVALS: "2"