name: E2E Test
on:
  pull_request:
    types: [ 'opened', 'synchronize' ]
    paths:
      - '.github/**'
      - '**.go'
      - '**.tf'
      - '**.md'
      - '**/go.mod'
env:
  ARM_SUBSCRIPTION_ID: "068245d4-3c94-42fe-9c4d-9e5e1cabc60c"
  ARM_TENANT_ID: "bcffb719-9620-4b7c-b1b0-87ebfb2f7bdd"
  ARM_CLIENT_ID: "78c646ba-5133-49f9-8968-c0f24611d988"
  ARM_CLIENT_SECRET: "~468Q~mcslSz2QdWYANY8PXldq0L~UA~A8tzGbxk"

jobs:
  acc-tests:
    runs-on: ubuntu-latest
    environment:
      name: acctests
    steps:
      - uses: actions/checkout@v3
      - name: init
        run: |
          docker run --rm -v $(pwd):/src -w /src mcr.microsoft.com/azterraform:latest make generate
      - name: e2e test
        run: |
          cat scripts/ci-e2e.sh
          echo --------
          sh scripts/ci-e2e.sh
      - name: upload test version snapshots
        uses: actions/upload-artifact@v3
        with:
          name: TestRecord-${{ github.event.number }}
          retention-days: 60
          path: |
            _example/**/TestRecord.md.tmp
      - name: version-upgrade test
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB }}
        run: |
          sh scripts/ci-version-upgrade.sh