name: E2E Test
on:
  pull_request:
    types: [ 'opened', 'synchronize' ]
    paths:
      - '.github/**'
      - '**.go'
      - '**.tf'
      - '**.md'
      - '**/go.mod'
env:
  MSI_ID: "/subscriptions/068245d4-3c94-42fe-9c4d-9e5e1cabc60c/resourcegroups/test/providers/Microsoft.ManagedIdentity/userAssignedIdentities/test-workflow"
  ARM_SUBSCRIPTION_ID: "${{ secrets.AZURE_SUBSCRIPTION_ID }}"
  ARM_TENANT_ID: "${{ secrets.AZURE_TENANT_ID }}"
  ARM_CLIENT_ID: "${{ secrets.AZURE_CLIENT_ID }}"
  ARM_CLIENT_SECRET: "${{ secrets.ARM_CLIENT_SECRET }}"

jobs:
  acc-tests:
    runs-on: ubuntu-latest
    environment:
      name: acctests
    steps:
      - uses: actions/checkout@v3
      
      # Install azure-cli
      - name: Install Azure CLI
        if: ${{ inputs.provider == 'azurerm' }}
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - name: init
        run: |
          docker run --rm -v $(pwd):/src -w /src mcr.microsoft.com/azterraform:latest make generate
      - name: e2e test
        run: |
          echo "my subscription id is $(echo $MSI_ID)"
          cat scripts/ci-e2e.sh
          echo --------
          sh scripts/ci-e2e.sh
      - name: upload test version snapshots
        uses: actions/upload-artifact@v3
        with:
          name: TestRecord-${{ github.event.number }}
          retention-days: 60
          path: |
            _example/**/TestRecord.md.tmp
      - name: version-upgrade test
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB }}
        run: |
          sh scripts/ci-version-upgrade.sh