name: E2E Test
on:
  pull_request:
    types: [ 'opened', 'synchronize' ]
    paths:
      - '.github/**'
      - '**.go'
      - '**.tf'
      - '**.md'
      - '**/go.mod'

jobs:
  acc-tests:
    runs-on: ubuntu-latest
    environment:
      name: acctests
    steps:
      - uses: actions/checkout@v3
      - name: init
        run: |
          echo 'SHELL := /bin/bash

          -include $(shell curl -sSL "https://raw.githubusercontent.com/Azure/tfmod-scaffold/main/scripts/install.sh" | bash -s > /dev/null ; echo tfmod-scaffold/GNUmakefile)

          init:
            @sh "$(CURDIR)/scripts/init.sh"

          cleanup:
            @sh "$(CURDIR)/scripts/cleanup.sh"' > GNUmakefile
          docker run --rm -v $(pwd):/src -w /src mcr.microsoft.com/azterraform:latest make generate
      - name: e2e test
        run: |
          sh scripts/ci-e2e.sh
      - name: upload test version snapshots
        uses: actions/upload-artifact@v3
        with:
          name: TestRecord-${{ github.event.number }}
          retention-days: 60
          path: |
            _example/**/TestRecord.md.tmp
      - name: version-upgrade test
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB }}
        run: |
          sh scripts/ci-version-upgrade.sh