name: readme
permissions: write-all
on:
  push:
    branches:
      - master
  workflow_dispatch:
jobs:
  tfsec:
    uses: clouddrove/github-shared-workflows/.github/workflows/tfsec.yml@master
    secrets: inherit
    with:
      working_directory: '.'