name: 'Create README.md file'
permissions: write-all

on:
  push:
    branches:
      - master
  workflow_dispatch:
jobs:
  readme:
    uses: clouddrove/github-shared-workflows/.github/workflows/readme.yml@master
    secrets: inherit