name: tf-drift
permissions:
  id-token: write
  contents: read
  issues: write
on:
  workflow_dispatch:
jobs:
  tf-drift:
    uses: clouddrove/test-action/.github/workflows/tf-drift.yml@master
    secrets: inherit
    with:
      working_directory: aws_example
      provider: 'aws'
      aws_region: 'eu-west-1'