name: Trigger Dependabot

on:
  workflow_run:
    workflows: ["Dependabot"]
    types:
      - completed

jobs:
  trigger:
    runs-on: ubuntu-latest
    steps:
    - name: Trigger Dependabot Update
      uses: actions/checkout@v2
    - run: echo "Triggering Dependabot update"
